### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/semeval16/restaurant_train.rawfre.graph'

### ISSUE THREAD

**Issue by snowblue2** [NLPWM-WHU/BiGCN#6]
maybe miss the program that generated the fre.graph

**Comment by NLPWM-WHU** [comment]
> maybe miss the program that generated the fre.graph

Hello, did you get this error while running the frequency_graph.py program? The restaurant_train.rawfre.graph file is required to run this program. Because the data set is too large, I did not upload it. I have uploaded all the data sets needed by the main program, and you can run the given command line directly. But now the dataset has been updated, I have uploaded it, please check.

**Comment by karimmahalian** [comment]
Hi,

@NLPWM-WHU  How to get this file restaurant_train.rawfre.graph' for a new data plz?

Thank u
